import type { Piece, PieceKind } from '../document/schema';

export type TerrainVisualState = 'normal' | 'hover' | 'selected' | 'multi-selected' | 'dragging' | 'resizing' | 'rotating' | 'valid' | 'invalid' | 'locked' | 'hidden' | 'disabled';
export type MeshPrimitive = 'box' | 'cylinder' | 'cone' | 'dodecahedron' | 'plane';
export interface MeshPart { primitive: MeshPrimitive; x: number; y: number; z: number; width: number; height: number; depth: number; material: string; }
export interface TerrainGeometry { kind: PieceKind; svgSymbol: string; mesh: readonly MeshPart[]; labelAnchor: { x: number; y: number }; }
const count = (span: number, preferred: number, minimum = 1) => Math.max(minimum, Math.floor(span / preferred));
const part = (primitive: MeshPrimitive, x: number, y: number, z: number, width: number, height: number, depth: number, material: string): MeshPart => ({ primitive, x, y, z, width, height, depth, material });
/** Renderer-neutral terrain grammar. Coordinates are local inches, never Three.js or SVG state. */
export function terrainGeometry(piece: Piece): TerrainGeometry { const w = piece.width; const h = piece.height; const structureHeight = piece.structureDetails?.heightInches ?? .45; const center = { x: w / 2, y: h / 2 };
  switch (piece.kind) {
    case 'building': return { kind: piece.kind, svgSymbol: 'building', labelAnchor: center, mesh: [part('box', w / 2, structureHeight / 2, .16, w, structureHeight, .32, 'building-wall'), part('box', w / 2, structureHeight / 2, h - .16, w, structureHeight, .32, 'building-wall'), part('box', .16, structureHeight / 2, h / 2, .32, structureHeight, Math.max(.32, h - .64), 'building-wall'), part('box', w - .16, structureHeight / 2, h / 2, .32, structureHeight, Math.max(.32, h - .64), 'building-wall'), part('box', w / 2, structureHeight + .03, h / 2, w, .06, h, piece.structureDetails?.roofMode === 'interior' ? 'interior' : 'roof')] };
    case 'ruin': return { kind: piece.kind, svgSymbol: 'ruin', labelAnchor: center, mesh: [part('box', .12, structureHeight / 2, h / 2, .24, structureHeight, h, 'ruin-wall'), part('box', w - .12, structureHeight / 3, h / 2, .24, structureHeight * .66, h, 'ruin-wall'), part('box', w / 2, structureHeight / 2, .12, w, structureHeight, .24, 'ruin-wall'), part('box', w / 2, structureHeight * .28, h - .12, w * .55, structureHeight * .56, .24, 'ruin-wall')] };
    case 'platform': return { kind: piece.kind, svgSymbol: 'platform', labelAnchor: center, mesh: [part('box', w / 2, structureHeight / 2, h / 2, w, structureHeight, h, 'platform')] };
    case 'road': return { kind: piece.kind, svgSymbol: 'road', labelAnchor: center, mesh: [part('plane', w / 2, .025, h / 2, w, .05, h, 'road')] };
    case 'water': return { kind: piece.kind, svgSymbol: 'water', labelAnchor: center, mesh: [part('plane', w / 2, .018, h / 2, w, .03, h, 'water')] };
    case 'wall': return { kind: piece.kind, svgSymbol: 'wall', labelAnchor: center, mesh: Array.from({ length: count(w, 1) }, (_, index) => part('box', index + .5, .5, h / 2, .78, 1, Math.max(.3, h), 'wall')) };
    case 'woods': return { kind: piece.kind, svgSymbol: 'woods', labelAnchor: center, mesh: Array.from({ length: count(w * h, 3, 3) }, (_, index) => part('cone', .65 + ((index * 1.9) % Math.max(1, w - 1.3)), 1.1, .65 + ((index * 1.37) % Math.max(1, h - 1.3)), .75, 2.1, .75, 'woods')) };
    case 'rocks': return { kind: piece.kind, svgSymbol: 'rocks', labelAnchor: center, mesh: Array.from({ length: count(w * h, 4, 2) }, (_, index) => part('dodecahedron', .7 + ((index * 1.65) % Math.max(1, w - 1.4)), .42, .65 + ((index * 1.17) % Math.max(1, h - 1.3)), .9, .8, .9, 'rocks')) };
    case 'scatter': return { kind: piece.kind, svgSymbol: 'scatter', labelAnchor: center, mesh: Array.from({ length: count(w * h, 2, 2) }, (_, index) => part('box', .4 + ((index * 1.1) % Math.max(.5, w - .8)), .28, .4 + ((index * .73) % Math.max(.5, h - .8)), .65, .55, .65, 'scatter')) };
    case 'objective': return { kind: piece.kind, svgSymbol: 'objective', labelAnchor: center, mesh: [part('cylinder', w / 2, .22, h / 2, Math.min(w, h) * .42, .44, Math.min(w, h) * .42, 'objective'), part('cone', w / 2, .72, h / 2, Math.min(w, h) * .3, .55, Math.min(w, h) * .3, 'objective')] };
    case 'token': return { kind: piece.kind, svgSymbol: 'token', labelAnchor: center, mesh: [part('cylinder', w / 2, .12, h / 2, Math.min(w, h) * .42, .24, Math.min(w, h) * .42, 'token')] };
    case 'marker': return { kind: piece.kind, svgSymbol: 'marker', labelAnchor: center, mesh: [part('cone', w / 2, .42, h / 2, Math.min(w, h) * .38, .84, Math.min(w, h) * .38, 'marker')] };
  }
}
export function terrainState(piece: Piece, selectedIds: readonly string[], hoveredId: string | null, transient: TerrainVisualState | null = null): TerrainVisualState { if (piece.hidden) return 'hidden'; if (transient) return transient; if (piece.locked) return 'locked'; if (selectedIds.includes(piece.id)) return selectedIds.length > 1 ? 'multi-selected' : 'selected'; return hoveredId === piece.id ? 'hover' : 'normal'; }
export interface TerrainLabel { id: string; x: number; y: number; width: number; detail: boolean; }
export function layoutTerrainLabels(pieces: readonly Piece[], selectedIds: readonly string[], hoveredId: string | null): TerrainLabel[] { const placed: TerrainLabel[] = []; const ranked = [...pieces].filter((piece) => !piece.hidden).sort((a, b) => Number(selectedIds.includes(b.id) || hoveredId === b.id) - Number(selectedIds.includes(a.id) || hoveredId === a.id)); for (const piece of ranked) { const geometry = terrainGeometry(piece); const detail = selectedIds.includes(piece.id) || hoveredId === piece.id; const width = Math.max(2.8, piece.name.length * .38 + (detail ? 2.2 : 0)); const candidate: TerrainLabel = { id: piece.id, x: piece.x + geometry.labelAnchor.x, y: piece.y + geometry.labelAnchor.y, width, detail }; const collides = placed.some((label) => Math.abs(label.x - candidate.x) < (label.width + candidate.width) / 2 && Math.abs(label.y - candidate.y) < .9); if (!collides || detail) placed.push(candidate); } return placed; }
