/* eslint-disable react-refresh/only-export-components */
import { Clipboard, Crosshair, Flag, History, MoveRight, Plus, Shield, Swords, Users } from 'lucide-react';
import type { BattleEvent, BattlePosition, BattleSession, BattleUnit } from '../simulation/contracts';
import type { RuleExplanation, TacticalAction } from '../simulation/rules';
import { deploymentZones } from '../simulation/deployment';
import { Button } from './components';

export interface UnitTemplate { id: string; name: string; role: string; }
export const unitTemplates: readonly UnitTemplate[] = [
  { id: 'scout', name: 'Scout team', role: 'Fast reconnaissance' },
  { id: 'line', name: 'Line team', role: 'Versatile fire team' },
  { id: 'heavy', name: 'Heavy team', role: 'Support element' },
];

export function RosterPanel({ session, selectedUnitId, onSelectUnit, onAddFaction, onAddUnit }: { session: BattleSession; selectedUnitId: string | null; onSelectUnit: (id: string) => void; onAddFaction: () => void; onAddUnit: (template: UnitTemplate) => void; }) {
  return <><section className="drawer-section"><span className="eyebrow">Factions</span><h3>Battle roster</h3><p>Roster edits reset deployment safely before a new session snapshot is saved.</p><div className="battle-faction-list">{session.factions.map((faction) => <div key={faction.id}><Shield size={14} /><span>{faction.name}</span><small>{session.units.filter((unit) => unit.factionId === faction.id).length} units</small></div>)}</div><Button variant="quiet" onClick={onAddFaction}><Plus size={14} />Add faction</Button></section><section className="drawer-section"><span className="eyebrow">Unit templates</span><h3>Add a unit</h3><div className="battle-template-list">{unitTemplates.map((template) => <Button key={template.id} variant="quiet" onClick={() => onAddUnit(template)}><Users size={14} /><span><strong>{template.name}</strong><small>{template.role}</small></span></Button>)}</div></section><section className="drawer-section"><span className="eyebrow">Roster units</span><h3>Unit cards</h3>{session.units.length ? <div className="battle-unit-list">{session.units.map((unit) => <UnitCard key={unit.id} unit={unit} factionName={session.factions.find((faction) => faction.id === unit.factionId)?.name ?? 'Unknown'} selected={unit.id === selectedUnitId} onSelect={() => onSelectUnit(unit.id)} />)}</div> : <p className="muted">Add a unit template to start deployment.</p>}</section></>;
}

function UnitCard({ unit, factionName, selected, onSelect }: { unit: BattleUnit; factionName: string; selected: boolean; onSelect: () => void; }) {
  return <button type="button" className={`battle-unit-card ${selected ? 'is-selected' : ''}`} aria-pressed={selected} onClick={onSelect}><Crosshair size={15} /><span><strong>{unit.name}</strong><small>{factionName} · {unit.position ? `${unit.position.x}, ${unit.position.y} deployed` : 'Awaiting deployment'}</small></span></button>;
}

export function DeploymentPanel({ session, selectedUnitId, position, onPosition, onDeploy }: { session: BattleSession; selectedUnitId: string | null; position: BattlePosition; onPosition: (position: BattlePosition) => void; onDeploy: () => void; }) {
  const selected = session.units.find((unit) => unit.id === selectedUnitId) ?? null;
  return <><section className="drawer-section"><span className="eyebrow">Deployment phase</span><h3>{selected ? `Deploy ${selected.name}` : 'Choose a unit card'}</h3><p>Generic checks require a faction zone, an unoccupied cell, and no blocking structure. Rules-specific validation starts in B15.</p></section><section className="drawer-section"><h3>Marked zones</h3><div className="battle-zone-list">{deploymentZones(session).map((zone) => <div key={zone.id}><strong>{zone.label}</strong><small>X {zone.x}–{zone.x + zone.width - 1} · all ranks</small></div>)}</div></section><section className="drawer-section"><h3>Grid position</h3><div className="field-grid"><label className="number-field"><span>X inch</span><input aria-label="Deployment X inch" type="number" min="0" max={session.board.snapshot.settings.widthInches - 1} value={position.x} onChange={(event) => onPosition({ ...position, x: Number(event.target.value) })} /></label><label className="number-field"><span>Y inch</span><input aria-label="Deployment Y inch" type="number" min="0" max={session.board.snapshot.settings.heightInches - 1} value={position.y} onChange={(event) => onPosition({ ...position, y: Number(event.target.value) })} /></label></div><Button variant="accent" disabled={!selected} onClick={onDeploy}>Deploy selected unit</Button></section></>;
}

export function BattleInspector({ session, unitId, onDeploy }: { session: BattleSession; unitId: string | null; onDeploy: () => void; }) {
  const unit = session.units.find((entry) => entry.id === unitId);
  if (!unit) return null;
  const faction = session.factions.find((entry) => entry.id === unit.factionId);
  return <aside className="battle-inspector" aria-label="Selected battle unit"><div className="inspector__header"><div><span className="eyebrow">Battle unit</span><h2>{unit.name}</h2></div><Crosshair size={20} /></div><div className="tabs__panel"><p><strong>Faction:</strong> {faction?.name ?? 'Unknown'}</p><p><strong>Status:</strong> {unit.position ? `Deployed at ${unit.position.x}, ${unit.position.y}` : 'Awaiting deployment'}</p><Button variant="accent" onClick={onDeploy}>{unit.position ? 'Reposition in Deploy' : 'Open deployment'}</Button></div></aside>;
}

export function BattleCommandPanel({ session, unitId, action, destination, targetId, explanation, onAction, onDestination, onTarget, onConfirm, onNextPhase }: { session: BattleSession; unitId: string | null; action: TacticalAction | null; destination: BattlePosition; targetId: string | null; explanation: RuleExplanation | null; onAction: (action: TacticalAction) => void; onDestination: (value: BattlePosition) => void; onTarget: (id: string) => void; onConfirm: () => void; onNextPhase: () => void; }) {
  const unit = session.units.find((entry) => entry.id === unitId) ?? null;
  const targets = session.units.filter((entry) => entry.id !== unitId && entry.position);
  return <><section className="drawer-section"><span className="eyebrow">Round {session.turn.round} · {session.turn.phase}</span><h3>{session.turn.activeFactionId ? `${session.factions.find((f) => f.id === session.turn.activeFactionId)?.name ?? 'Active faction'} command` : 'Battle transition'}</h3><p>{unit ? `Selected: ${unit.name}. Choose an action, inspect the deterministic preview, then explicitly confirm.` : 'Select a deployed unit on the board or from the roster.'}</p><Button variant="accent" onClick={onNextPhase}>Advance phase</Button></section>
    <section className="drawer-section"><span className="eyebrow">Action selection</span><h3>Command action</h3><div className="battle-action-list"><Button variant={action === 'move' ? 'accent' : 'quiet'} disabled={!unit} onClick={() => onAction('move')}><MoveRight size={14} />Move</Button><Button variant={action === 'attack' ? 'accent' : 'quiet'} disabled={!unit} onClick={() => onAction('attack')}><Swords size={14} />Attack</Button><Button variant={action === 'secure-objective' ? 'accent' : 'quiet'} disabled={!unit} onClick={() => onAction('secure-objective')}><Flag size={14} />Secure objective</Button></div></section>
    {action === 'move' && <section className="drawer-section"><h3>Movement preview</h3><div className="field-grid"><label className="number-field"><span>X inch</span><input aria-label="Movement destination X" type="number" min="0" max={session.board.snapshot.settings.widthInches - 1} value={destination.x} onChange={(event) => onDestination({ ...destination, x: Number(event.target.value) })} /></label><label className="number-field"><span>Y inch</span><input aria-label="Movement destination Y" type="number" min="0" max={session.board.snapshot.settings.heightInches - 1} value={destination.y} onChange={(event) => onDestination({ ...destination, y: Number(event.target.value) })} /></label></div></section>}
    {action === 'attack' && <section className="drawer-section"><h3>Target / range / sight</h3><div className="battle-unit-list">{targets.map((target) => <button key={target.id} type="button" className={`battle-unit-card ${target.id === targetId ? 'is-selected' : ''}`} onClick={() => onTarget(target.id)}><Crosshair size={14} /><span><strong>{target.name}</strong><small>{target.position!.x}, {target.position!.y} · inspect range, LOS, and cover below</small></span></button>)}</div></section>}
    {action === 'secure-objective' && <section className="drawer-section"><h3>Objective interaction</h3><p>{session.objectives.length ? 'The selected unit will attempt to secure the first board-anchored objective. The rule calculation below explains control or contesting.' : 'This board has no objective terrain. Add an objective in Build mode, then start a fresh battle session.'}</p></section>}
    {explanation && <Explanation explanation={explanation} />}
    <section className="drawer-section"><Button variant="accent" disabled={!action || !explanation || explanation.outcome === 'illegal'} onClick={onConfirm}>Confirm {action?.replace('-', ' ') ?? 'action'}</Button><p className="battle-confirm-hint">Confirmation records the deterministic command and its audit trail. Illegal previews never mutate the live session.</p></section></>;
}

export function Explanation({ explanation }: { explanation: RuleExplanation }) { return <section className={`drawer-section battle-explanation battle-explanation--${explanation.outcome}`} aria-live="polite"><span className="eyebrow">Calculation detail · {explanation.outcome}</span><h3>{explanation.title}</h3><p>{explanation.summary}</p>{explanation.inputs.length > 0 && <dl>{explanation.inputs.map((entry) => <div key={entry.label}><dt>{entry.label}</dt><dd>{entry.value}</dd></div>)}</dl>}{explanation.terrain.length > 0 && <p><strong>Terrain:</strong> {explanation.terrain.join('; ')}</p>}{explanation.rolls.map((roll) => <p key={roll.label}><strong>{roll.label}:</strong> {roll.result} ({roll.minimum}–{roll.maximum}, target {roll.target ?? '—'})</p>)}</section>; }

const eventSummary = (event: BattleEvent) => event.type.replaceAll('.', ' ').replaceAll(/\b\w/g, (letter) => letter.toUpperCase());
export function BattleLogPanel({ session, filter, onFilter, replayIndex, onReplayIndex, onCopySeed }: { session: BattleSession; filter: 'all' | 'roll' | 'phase' | 'action'; onFilter: (value: 'all' | 'roll' | 'phase' | 'action') => void; replayIndex: number | null; onReplayIndex: (value: number | null) => void; onCopySeed: () => void; }) {
  const events = session.events.filter((event) => filter === 'all' || filter === 'roll' && event.type.includes('roll') || filter === 'phase' && event.type.includes('phase') || filter === 'action' && (event.type.includes('move') || event.type.includes('objective') || event.type.includes('deploy')));
  return <><section className="drawer-section"><span className="eyebrow">Replay and random seed</span><h3>{replayIndex === null ? 'Live session' : `Read-only replay · event ${replayIndex}`}</h3><p>Seed <code>{session.seed}</code></p><Button variant="quiet" onClick={onCopySeed}><Clipboard size={14} />Copy deterministic seed</Button><div className="battle-replay-controls"><Button variant="quiet" disabled={replayIndex === null || replayIndex <= 0} onClick={() => onReplayIndex(Math.max(0, (replayIndex ?? 0) - 1))}>Previous</Button><Button variant="quiet" onClick={() => onReplayIndex(replayIndex === null ? session.events.length : null)}>{replayIndex === null ? 'Enter replay' : 'Return live'}</Button><Button variant="quiet" disabled={replayIndex === null || replayIndex >= session.events.length} onClick={() => onReplayIndex(Math.min(session.events.length, (replayIndex ?? 0) + 1))}>Next</Button></div></section><section className="drawer-section"><span className="eyebrow">Event history</span><h3><History size={14} /> Audit log</h3><div className="battle-log-filters">{(['all', 'roll', 'phase', 'action'] as const).map((value) => <Button key={value} variant={filter === value ? 'accent' : 'quiet'} onClick={() => onFilter(value)}>{value}</Button>)}</div><ol className="battle-event-log">{events.map((event) => <li key={event.sequence}><strong>#{event.sequence} {eventSummary(event)}</strong><small>{event.type === 'roll.resolved' ? `Result ${event.result} on ${event.minimum}–${event.maximum}` : event.type === 'move.intent.recorded' ? `Destination ${event.destination.x}, ${event.destination.y}` : event.type === 'objective.state.changed' ? event.state : new Date(event.at).toLocaleTimeString()}</small></li>)}</ol></section></>;
}
