/* eslint-disable react-hooks/exhaustive-deps */
import { useEffect, useMemo, useState } from 'react';
import { Copy, Eye, EyeOff, Link2, LockKeyhole, MoveDown, MoveUp, Search, Trash2 } from 'lucide-react';
import type { BoardDocument, Piece, PieceKind } from '../document/schema';
import { catalog, catalogByKind } from '../model/catalog';
import { normalizeRotation, resizePiece } from '../model/board-operations';
import { Button, NumberField, Tabs } from './components';

export function BoardPanel({ board, onHelp }: { board: BoardDocument; onHelp: () => void }) {
  return <><section className="drawer-section"><h3>{board.name}</h3><p>{board.pieces.length} pieces · {board.settings.widthInches} × {board.settings.heightInches} inches · local draft pending lifecycle controls.</p></section><section className="drawer-section"><h3>Board help</h3><p>Build opens a catalog, Layers finds and manages placed terrain, and Setup owns board-scale settings.</p><Button variant="quiet" onClick={onHelp}>Open controls reference</Button></section></>;
}

export function BuildPanel({ activeKind, onChoose }: { activeKind: PieceKind; onChoose: (kind: PieceKind) => void }) {
  const [query, setQuery] = useState(''); const [expanded, setExpanded] = useState<string | null>('Structures'); const normalized = query.trim().toLocaleLowerCase(); const matches = (item: typeof catalog[number]) => !normalized || `${item.name} ${item.singular} ${item.group} ${item.description}`.toLocaleLowerCase().includes(normalized);
  const favourite = catalog.filter((item) => item.favourite && matches(item)); const recent = catalog.filter((item) => item.recent && matches(item)); const groups = useMemo(() => catalog.filter(matches).reduce<Record<string, typeof catalog>>((all, item) => ({ ...all, [item.group]: [...(all[item.group] ?? []), item] }), {}), [normalized]);
  const Item = ({ item }: { item: typeof catalog[number] }) => <button className={`catalog-item ${activeKind === item.kind ? 'is-selected' : ''}`} type="button" onClick={() => onChoose(item.kind)}><span><strong>{item.name}</strong><small>{item.width} × {item.height} in · {item.description}</small></span><span aria-hidden="true">+</span></button>;
  return <><label className="search-field"><span className="sr-only">Search terrain catalog</span><span className="search-field__icon"><Search size={14} /></span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search terrain" /></label>{favourite.length > 0 && <section className="drawer-section"><h3>Favorites</h3>{favourite.map((item) => <Item key={`favorite-${item.kind}`} item={item} />)}</section>}{recent.length > 0 && <section className="drawer-section"><h3>Recent</h3>{recent.map((item) => <Item key={`recent-${item.kind}`} item={item} />)}</section>}{Object.entries(groups).map(([group, items]) => { const open = Boolean(normalized) || expanded === group; return <section className="drawer-section" key={group}><button className="catalog-group" type="button" aria-expanded={open} onClick={() => setExpanded(open ? null : group)}><span>{group}</span><span aria-hidden="true">{open ? '−' : '+'}</span></button>{open && items.map((item) => <Item key={item.kind} item={item} />)}</section>; })}{!Object.keys(groups).length && <p className="drawer-empty">No terrain matches “{query}”.</p>}<p className="drawer-hint">Choose a tool to arm Build immediately, then drag an inch-snapped footprint on the board.</p></>;
}

export function LayersPanel({ board, selectedIds, onSelect, onChangePieces, onReorder }: { board: BoardDocument; selectedIds: readonly string[]; onSelect: (ids: string[]) => void; onChangePieces: (ids: readonly string[], change: Partial<Pick<Piece, 'locked' | 'hidden'>>) => void; onReorder: (ids: readonly string[], direction: -1 | 1) => void }) {
  const [query, setQuery] = useState(''); const shown = board.pieces.slice().sort((left, right) => right.layer - left.layer).filter((piece) => `${piece.name} ${piece.kind}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())); const selected = board.pieces.filter((piece) => selectedIds.includes(piece.id)); const mixed = (key: 'locked' | 'hidden') => new Set(selected.map((piece) => piece[key])).size > 1;
  return <><label className="search-field"><span className="sr-only">Search layers</span><span className="search-field__icon"><Search size={14} /></span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search placed terrain" /></label>{selected.length > 0 && <section className="layer-actions"><strong>{selected.length} selected</strong><div><Button variant="quiet" onClick={() => onChangePieces(selectedIds, { locked: mixed('locked') || !selected.every((piece) => piece.locked) })}><LockKeyhole size={14} />{selected.every((piece) => piece.locked) ? 'Unlock' : 'Lock'}</Button><Button variant="quiet" onClick={() => onChangePieces(selectedIds, { hidden: mixed('hidden') || !selected.every((piece) => piece.hidden) })}>{selected.every((piece) => piece.hidden) ? <Eye size={14} /> : <EyeOff size={14} />}{selected.every((piece) => piece.hidden) ? 'Show' : 'Hide'}</Button><Button variant="quiet" onClick={() => onReorder(selectedIds, 1)}><MoveUp size={14} />Raise</Button><Button variant="quiet" onClick={() => onReorder(selectedIds, -1)}><MoveDown size={14} />Lower</Button></div></section>}<section className="drawer-section"><h3>Placed terrain</h3>{shown.map((piece) => <button className={`layer-item ${selectedIds.includes(piece.id) ? 'is-selected' : ''}`} type="button" key={piece.id} onClick={(event) => onSelect(event.shiftKey ? (selectedIds.includes(piece.id) ? selectedIds.filter((id) => id !== piece.id) : [...selectedIds, piece.id]) : [piece.id])}><span className="layer-item__state" aria-hidden="true">{piece.hidden ? '◌' : piece.locked ? '◆' : '●'}</span><span><strong>{piece.name}</strong><small>{piece.kind} · layer {piece.layer} · {piece.width} × {piece.height} in</small></span></button>)}{!shown.length && <p className="drawer-empty">No placed terrain matches “{query}”.</p>}</section></>;
}

export function SetupPanel({ board, onSettings }: { board: BoardDocument; onSettings: (settings: BoardDocument['settings']) => void }) {
  const settings = board.settings; const commit = (change: Partial<BoardDocument['settings']>) => onSettings({ ...settings, ...change });
  return <><section className="drawer-section"><h3>Board dimensions</h3><div className="field-grid"><NumberField label="Width (in)" value={settings.widthInches} min={12} max={72} onCommit={(widthInches) => commit({ widthInches: Math.round(widthInches) })} /><NumberField label="Height (in)" value={settings.heightInches} min={12} max={72} onCommit={(heightInches) => commit({ heightInches: Math.round(heightInches) })} /></div><p className="drawer-hint">Range: 12–72 inches. The permanent grid is exactly one inch per cell; smaller dimensions cannot clip placed terrain.</p></section><section className="drawer-section"><h3>Orientation</h3><div className="segmented"><Button variant={settings.orientation === 'landscape' ? 'accent' : 'quiet'} onClick={() => commit({ orientation: 'landscape' })}>Landscape</Button><Button variant={settings.orientation === 'portrait' ? 'accent' : 'quiet'} onClick={() => commit({ orientation: 'portrait' })}>Portrait</Button></div></section><section className="drawer-section"><h3>Surface</h3><div className="surface-options">{(['midnight', 'concrete', 'sand'] as const).map((surface) => <Button key={surface} variant={settings.surface === surface ? 'accent' : 'quiet'} onClick={() => commit({ surface })}>{surface}</Button>)}</div></section><section className="drawer-section"><h3>Placement</h3><Button variant={settings.snap ? 'accent' : 'quiet'} aria-pressed={settings.snap} onClick={() => commit({ snap: !settings.snap })}>{settings.snap ? 'Snap on' : 'Snap off'}</Button><p className="drawer-hint">The visible one-inch grid never changes. Snap controls placement behavior only.</p></section></>;
}

type AccessType = 'door' | 'window';
export function InspectorPanel({ piece, selectionCount, accessType, onAccessType, onPatch, onDelete, onDuplicate, onJoin, joinReason, onRemoveAccess }: { piece: Piece | null; selectionCount: number; accessType: AccessType; onAccessType: (type: AccessType) => void; onPatch: (change: Partial<Piece>) => void; onDelete: () => void; onDuplicate: () => void; onJoin: () => void; joinReason: string | null; onRemoveAccess: (id: string) => void }) {
  const [tab, setTab] = useState('properties'); const [name, setName] = useState(piece?.name ?? ''); const [notes, setNotes] = useState(piece?.notes ?? ''); useEffect(() => { setName(piece?.name ?? ''); setNotes(piece?.notes ?? ''); setTab('properties'); }, [piece?.id]); if (!piece) return null;
  const structure = piece.structureDetails; const setDimensions = (key: 'width' | 'height', value: number) => onPatch(resizePiece(piece, key === 'width' ? value : piece.width, key === 'height' ? value : piece.height));
  const properties = <div className="inspector-fields"><label className="text-field"><span>Name</span><input value={name} onChange={(event) => setName(event.target.value)} onBlur={() => { const next = name.trim(); if (next && next !== piece.name) onPatch({ name: next }); }} /></label><p>{selectionCount > 1 ? `${selectionCount} objects selected. Numeric edits apply to the active item.` : catalogByKind(piece.kind).description}</p><div className="field-grid"><NumberField label="X (in)" value={piece.x} min={0} max={71} onCommit={(x) => onPatch({ x: Math.round(x) })} /><NumberField label="Y (in)" value={piece.y} min={0} max={71} onCommit={(y) => onPatch({ y: Math.round(y) })} /><NumberField label="Width (in)" value={piece.width} min={catalogByKind(piece.kind).bounds.minWidth} max={catalogByKind(piece.kind).bounds.maxWidth} onCommit={(width) => setDimensions('width', width)} /><NumberField label="Height (in)" value={piece.height} min={catalogByKind(piece.kind).bounds.minHeight} max={catalogByKind(piece.kind).bounds.maxHeight} onCommit={(height) => setDimensions('height', height)} /><NumberField label="Rotation" value={piece.rotation} min={0} max={359} onCommit={(rotation) => onPatch({ rotation: normalizeRotation(rotation) })} /></div><div className="inspector-actions"><Button variant="quiet" onClick={() => onPatch({ locked: !piece.locked })}><LockKeyhole size={14} />{piece.locked ? 'Unlock' : 'Lock'}</Button><Button variant="quiet" onClick={() => onPatch({ hidden: !piece.hidden })}>{piece.hidden ? <Eye size={14} /> : <EyeOff size={14} />}{piece.hidden ? 'Show' : 'Hide'}</Button><Button variant="quiet" onClick={onDuplicate}><Copy size={14} />Duplicate</Button><Button variant="danger" onClick={onDelete}><Trash2 size={14} />Delete</Button></div>{selectionCount > 1 && <div className="join-block"><Button variant="accent" onClick={onJoin} disabled={Boolean(joinReason)}><Link2 size={14} />Join structures</Button>{joinReason && <small>{joinReason}</small>}</div>}</div>;
  const appearance = <div className="inspector-fields"><p>Rendering follows the shared terrain catalog so overhead and 3D planning stay aligned.</p><NumberField label="Layer" value={piece.layer} min={-1000} max={1000} onCommit={(layer) => onPatch({ layer: Math.round(layer) })} /><p className="drawer-hint">Higher layers display above lower layers. Use Layers for multi-item ordering.</p></div>;
  const structureContent = structure ? <div className="inspector-fields"><div className="field-grid"><NumberField label="Height (in)" value={structure.heightInches} min={1} max={72} onCommit={(heightInches) => onPatch({ structureDetails: { ...structure, heightInches: Math.round(heightInches) } })} /><NumberField label="Elevation (in)" value={structure.elevationInches} min={-72} max={72} onCommit={(elevationInches) => onPatch({ structureDetails: { ...structure, elevationInches: Math.round(elevationInches) } })} /></div><Button variant="quiet" onClick={() => onPatch({ structureDetails: { ...structure, roofMode: structure.roofMode === 'roof' ? 'interior' : 'roof' } })}>Roof treatment: {structure.roofMode === 'roof' ? 'Roof' : 'Interior'}</Button><p className="drawer-hint">Direct handles are available in Select mode.</p></div> : <p>This terrain has no structure details.</p>;
  const access = structure && piece.kind !== 'platform' ? <div className="inspector-fields"><p>Choose a feature, then use Access mode and click an exterior wall.</p><div className="segmented"><Button variant={accessType === 'door' ? 'accent' : 'quiet'} onClick={() => onAccessType('door')}>Door</Button><Button variant={accessType === 'window' ? 'accent' : 'quiet'} onClick={() => onAccessType('window')}>Window</Button></div>{[['Doors', structure.doors], ['Windows', structure.windows]].map(([label, features]) => <div className="access-list" key={label as string}><strong>{label as string}</strong>{(features as typeof structure.doors).length ? (features as typeof structure.doors).map((feature) => <div key={feature.id}><span>{feature.wall} · {feature.offset + 1}–{feature.offset + feature.span} in</span><Button variant="quiet" onClick={() => onRemoveAccess(feature.id)}>Remove</Button></div>) : <small>None</small>}</div>)}</div> : <p>Doors and windows are supported on buildings and ruins only.</p>;
  const notesContent = <div className="inspector-fields"><label className="text-field"><span>Planner notes</span><textarea value={notes} maxLength={2000} onChange={(event) => setNotes(event.target.value)} onBlur={() => { if (notes !== piece.notes) onPatch({ notes }); }} placeholder="Add tactical notes…" /></label><small>{notes.length}/2000</small></div>;
  const tabs = [{ id: 'properties', label: 'Properties', content: properties }, { id: 'appearance', label: 'Appearance', content: appearance }, ...(structure ? [{ id: 'structure', label: 'Structure', content: structureContent }, { id: 'access', label: 'Access', content: access }] : []), { id: 'notes', label: 'Notes', content: notesContent }];
  return <aside className="inspector" aria-label={`${piece.name} inspector`}><div className="inspector__header"><div><p className="eyebrow">Selected terrain</p><h2>{piece.name}</h2></div></div><Tabs selected={tab} onSelect={setTab} tabs={tabs} /></aside>;
}
