import { useEffect, useRef } from 'react';
import * as THREE from 'three';
import type { BoardDocument } from '../document/schema';

export type ThreePreset = 'top' | 'isometric' | 'perspective' | 'front';
export function ThreeBoard({ board, preset, onSelect }: { board: BoardDocument; preset: ThreePreset; onSelect?: (id: string | null) => void }) {
  const host = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const element = host.current; if (!element) return undefined;
    const renderer = new THREE.WebGLRenderer({ antialias: true, powerPreference: 'high-performance' }); renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); element.append(renderer.domElement);
    const scene = new THREE.Scene(); scene.background = new THREE.Color(board.settings.surface === 'sand' ? '#292319' : board.settings.surface === 'concrete' ? '#202326' : '#08131e');
    const camera = new THREE.PerspectiveCamera(45, 1, .1, 300); const size = Math.max(board.settings.widthInches, board.settings.heightInches); const target = new THREE.Vector3(board.settings.widthInches / 2, 0, board.settings.heightInches / 2);
    const setPreset = () => { const poses: Record<ThreePreset, [number, number, number]> = { top: [size / 2, size * 1.6, size / 2.01], isometric: [size * 1.15, size, size * 1.15], perspective: [size * 1.25, size * .55, size * 1.35], front: [size / 2, size * .38, size * 1.5] }; camera.position.set(...poses[preset]); camera.lookAt(target); }; setPreset();
    const grid = new THREE.GridHelper(size, size, 0x59cbd6, 0x294b57); grid.position.set(size / 2, 0, size / 2); scene.add(grid);
    const major = new THREE.LineBasicMaterial({ color: 0x78edf5 }); for (let i = 0; i <= size; i += 12) { const a = new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(i, .01, 0), new THREE.Vector3(i, .01, size)]); const b = new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(0, .01, i), new THREE.Vector3(size, .01, i)]); scene.add(new THREE.Line(a, major), new THREE.Line(b, major)); }
    const material = new THREE.MeshStandardMaterial({ color: 0x1f91a1, roughness: .75 }); board.pieces.filter((piece) => !piece.hidden).forEach((piece) => { const mesh = new THREE.Mesh(new THREE.BoxGeometry(piece.width, piece.structureDetails?.heightInches ?? .6, piece.height), material.clone()); mesh.position.set(piece.x + piece.width / 2, (piece.structureDetails?.heightInches ?? .6) / 2, piece.y + piece.height / 2); mesh.userData.id = piece.id; scene.add(mesh); });
    scene.add(new THREE.HemisphereLight(0xaeeeff, 0x101820, 2)); const raycaster = new THREE.Raycaster(); const pointer = new THREE.Vector2(); let orbit = false; let pan = false; let last = { x: 0, y: 0 }; const onPointerDown = (event: PointerEvent) => { orbit = event.button === 2 || event.altKey; pan = event.button === 1 || event.shiftKey; last = { x: event.clientX, y: event.clientY }; renderer.domElement.setPointerCapture(event.pointerId); }; const onPointerMove = (event: PointerEvent) => { if (!orbit && !pan) return; const dx = event.clientX - last.x; const dy = event.clientY - last.y; last = { x: event.clientX, y: event.clientY }; if (orbit) { camera.position.applyAxisAngle(new THREE.Vector3(0, 1, 0), -dx * .008); camera.position.y = Math.max(3, camera.position.y + dy * .08); camera.lookAt(target); } else { camera.position.x -= dx * .05; camera.position.z -= dy * .05; target.x -= dx * .05; target.z -= dy * .05; camera.lookAt(target); } }; const onPointerUp = (event: PointerEvent) => { if (!orbit && !pan) { const rect = renderer.domElement.getBoundingClientRect(); pointer.set(((event.clientX - rect.left) / rect.width) * 2 - 1, -((event.clientY - rect.top) / rect.height) * 2 + 1); raycaster.setFromCamera(pointer, camera); onSelect?.(raycaster.intersectObjects(scene.children, true)[0]?.object.userData.id ?? null); } orbit = false; pan = false; }; const onWheel = (event: WheelEvent) => { event.preventDefault(); camera.position.multiplyScalar(event.deltaY < 0 ? .9 : 1.1); camera.lookAt(target); }; renderer.domElement.addEventListener('pointerdown', onPointerDown); renderer.domElement.addEventListener('pointermove', onPointerMove); renderer.domElement.addEventListener('pointerup', onPointerUp); renderer.domElement.addEventListener('wheel', onWheel, { passive: false }); renderer.domElement.addEventListener('contextmenu', (event) => event.preventDefault());
    let frame = 0; const onContextLost = (event: Event) => { event.preventDefault(); element.dataset.contextLost = 'true'; }; const resize = () => { const { width, height } = element.getBoundingClientRect(); renderer.setSize(width, height); camera.aspect = width / height; camera.updateProjectionMatrix(); }; const render = () => { frame = requestAnimationFrame(render); renderer.render(scene, camera); }; renderer.domElement.addEventListener('webglcontextlost', onContextLost); resize(); const observer = new ResizeObserver(resize); observer.observe(element); render(); return () => { cancelAnimationFrame(frame); observer.disconnect(); renderer.domElement.removeEventListener('webglcontextlost', onContextLost); renderer.dispose(); element.replaceChildren(); };
  }, [board, onSelect, preset]);
  return <div ref={host} className="three-board" role="application" aria-label="Interactive 3D planning board" tabIndex={0} />;
}
